version: '3'
services:
  postgres:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./init/init_postgres.sh:/docker-entrypoint-initdb.d/init_postgres.sh 

  oracle:
    build:
      context: .
      dockerfile: Dockerfile.oracle
    container_name: oracle_db
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
    ports:
      - "1521:1521"
    volumes:
      - ./init-scripts:/init-scripts 
