services:
  postgres:
    build: 
      context: .
      dockerfile: Dockerfile.postgres
    container_name: postgres_ods
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts/init_postgres.sh:/docker-entrypoint-initdb.d/init_postgres.sh
      # SQL file to create schema and tables
      - ./init-scripts/init_schema.sql:/docker-entrypoint-initdb.d/init_schema.sql
    profiles:
      - postgres_ods

  oracle:
    build:
      context: .
      dockerfile: Dockerfile.oracle
    container_name: oracle_lrm
    env_file:
      - ./.env
    environment:
      ORACLE_PASSWORD: ${ORACLE_PASSWORD}
    ports:
      - "1521:1521"
    volumes:
      - ./init-scripts:/init-scripts 
    profiles:
      - oracle_lrm
