FROM container-registry.oracle.com/database/express:latest

# Copy initialization scripts into the container
COPY ./init-scripts /init-scripts

# Set environment variables for Oracle 
ENV ORACLE_PASSWORD=${ORACLE_PASSWORD}

# Expose Oracle DB port
EXPOSE 1521

# Run the initialization script during container startup
CMD ["/bin/bash", "/init-scripts/init_oracle.sh"]
