apiVersion: v1
kind: Secret
metadata:
  name: lrm-ods-database
type: Opaque
stringData:
  ODS_USERNAME: ods_proxy_user_lrm
  ODS_PASSWORD: ods_proxy_user_lrm
  ODS_HOST: 172.28.0.10
  ODS_PORT: '5432'
  ODS_DATABASE: ods
  MSTR_SCHEMA: FOREST
  APP_NAME: bcts_replication
  CONCUR_TASKS: '1'

---

apiVersion: v1
kind: Secret
metadata:
  name: lrm-database
type: Opaque
stringData:
  DB_USERNAME: FOREST
  DB_PASSWORD: admin_password
  DB_HOST: oracle.nrids-bcts-data_ods_network
  DB_PORT: '1521'
  DATABASE: LRM



 