CREATE OR REPLACE VIEW BCTS_STAGING.V_LRM_LICENCE AS
SELECT                                                           --DISTINCT
	 LRM_REPLICATION.LICENCE_ALLOCATION.MANU_SEQ_NBR,
	  LRM_REPLICATION.LICENCE.DIVI_DIV_NBR,
	  LRM_REPLICATION.LICENCE.LICN_SEQ_NBR,
	  LRM_REPLICATION.LICENCE.LICN_DIGI_IND,
	  LRM_REPLICATION.LICENCE.LICN_LICENCE_ID,
	  LRM_REPLICATION.LICENCE.LICN_CATEGORY_ID,
	  CAST (LRM_REPLICATION.LICENCE.LICN_CROWN_LAND AS VARCHAR (3))
		 AS LICN_CROWN_LAND,
	  LRM_REPLICATION.LICENCE.LICN_CROWN_GRANTED_IND,
	  LRM_REPLICATION.LICENCE.BLAZ_ADMIN_ZONE_ID,
	  LRM_REPLICATION.LICENCE.LICL_LICENCE_CLASS,
	  LRM_REPLICATION.LICENCE.LICN_PARENT_LICENCE,
	  LRM_REPLICATION.LICENCE.LICN_LICENCE_DESC,
	  LRM_REPLICATION.LICENCE.LICN_LICENCE_TO_CUT_CODE,
	  LRM_REPLICATION.LICENCE.LICN_PERMIT_EXISTS_IND,
	  LRM_REPLICATION.LICENCE.LICN_LICENCE_STATE,
	  LRM_REPLICATION.LICENCE.LICN_ANNUAL_ALLOWABLE_CUT,
	  LRM_REPLICATION.LICENCE.LSEE_LICENSEE_ID,
	  LRM_REPLICATION.LICENSEE.LSEE_CLIENT_CODE,
	  --BLAL_CALC.GROSS_AREA,
	  --sq18542 get from cut_block
	  --(SELECT NVL (SUM (V.CUTB_GROSS_HA_AREA), 0)
	  --   FROM LRM_REPLICATION.V_LRM_CUT_BLOCK V
	  -- WHERE V.LICN_SEQ_NBR = LRM_REPLICATION.LICENCE.LICN_SEQ_NBR)
	  --   AS GROSS_AREA,
	  --sq18780 get from licence shape record
	  LS.GROSS_AREA,                    --Rounding added in 18901 fixes
	  CAST (LRM_REPLICATION.LICENCE.LICN_CLIENT_LOCATION_CODE AS VARCHAR (5))
		 AS LICN_CLIENT_LOCATION_CODE,
	  LRM_REPLICATION.LICENCE.LICN_SALVAGE_IND,
	  LRM_REPLICATION.LICENCE.LICN_APPORTION_TENURE_TYPE,
	  LRM_REPLICATION.LICENCE.CTOR_SEQ_NBR,
	  LRM_REPLICATION.LICENCE.TENT_SEQ_NBR,
	  LRM_REPLICATION.LICENCE.LINC_CERT_LEVEL_ID,
	  LRM_REPLICATION.LICENCE.LICN_FIELD_TEAM_ID,
	  LRM_REPLICATION.LICENCE.LICN_HAMMERMARK,
	  LRM_REPLICATION.LICENCE.MODIFIEDBY,
	  LRM_REPLICATION.LICENCE.MODIFIEDON,
	  LRM_REPLICATION.LICENCE.MODIFIEDUSING,
	  LRM_REPLICATION.LICENCE.CREATEDBY,
	  LRM_REPLICATION.LICENCE.CREATEDON,
	  LRM_REPLICATION.LICENCE.CREATEDUSING,
	  ROUND (BLAL_CALC.MERCHANTABLE_AREA, 1) AS MERCHANTABLE_AREA, --Rounding added in 18901 fixes
	  ROUND (
		 BCTS_STAGING.SF_CALC_LICENCE_HARV_AREA(
			LICENCE_ALLOCATION.LICN_SEQ_NBR,
			LICENCE_ALLOCATION.MANU_SEQ_NBR),
		 1)
		 AS HARVESTED_AREA,                --Rounding added in 18901 fixes
	  ROUND (
		 BCTS_STAGING.SF_CALC_LICENCE_STANDING_AREA (
			LICENCE_ALLOCATION.LICN_SEQ_NBR,
			LICENCE_ALLOCATION.MANU_SEQ_NBR),
		 1)
		 AS STANDING_AREA,                 --Rounding added in 18901 fixes
	  ROUND (BLAL_CALC.CRUISE_VOLUME, 0) AS CRUISE_VOLUME, --Rounding added in 18901 fixes
	  ROUND (BLAL_CALC.HARVESTED_VOLUME, 0) AS HARVESTED_VOLUME, --Rounding added in 18901 fixes
	  ROUND (BLAL_CALC.STANDING_VOLUME, 0) AS STANDING_VOLUME, --Rounding added in 18901 fixes
	  ROUND ( (BLAL_CALC.CRUISE_VOLUME - BLAL_CALC.HARVESTED_VOLUME), 0)
		 AS CRUISE_VARIANCE,               --Rounding added in 18901 fixes
	  CASE
        WHEN COUNT(LRM_REPLICATION.LICENCE_ALLOCATION.LICN_SEQ_NBR) OVER (PARTITION BY LRM_REPLICATION.LICENCE.LICN_SEQ_NBR) > 0 
        THEN 'Y'
        ELSE 'N'
    END AS V_LOCK_FIELD,
	  COALESCE(CS.NO_SHAPE, 1) AS NO_SHAPE,
	  LRM_REPLICATION.LICENCE.LICN_ARCHIVE_IND,
	  LRM_REPLICATION.LICENCE.LICN_ARCHIVE_DATE
 FROM LRM_REPLICATION.LICENSEE
	  RIGHT JOIN LRM_REPLICATION.LICENCE
		 ON (LRM_REPLICATION.LICENCE.LSEE_LICENSEE_ID =
				LRM_REPLICATION.LICENSEE.LSEE_LICENSEE_ID)
	  LEFT JOIN LRM_REPLICATION.LICENCE_ALLOCATION
		 ON (LRM_REPLICATION.LICENCE.LICN_SEQ_NBR =
				LRM_REPLICATION.LICENCE_ALLOCATION.LICN_SEQ_NBR)
	  LEFT JOIN
	  (  SELECT LICN_SEQ_NBR,
				SUM (COALESCE (BLAL_GROSS_HA_AREA, 0)) GROSS_AREA,
				SUM (COALESCE (BLAL_MERCH_HA_AREA, 0)) MERCHANTABLE_AREA,
				SUM (COALESCE (BLAL_CRUISE_M3_VOL, 0)) CRUISE_VOLUME,
				SUM (COALESCE (BLAL_HARVESTED_M3_VOL, 0)) HARVESTED_VOLUME,
				SUM (
				   CASE
					  WHEN BLAL_MERCH_HA_AREA = BLAL_HARVESTED_HA_AREA
					  THEN
						 0
					  ELSE
						   BLAL_CRUISE_M3_VOL
						 - COALESCE (BLAL_HARVESTED_M3_VOL, 0)
				   END)
				   STANDING_VOLUME
		   FROM LRM_REPLICATION.BLOCK_ALLOCATION
	   GROUP BY LICN_SEQ_NBR) BLAL_CALC
		 ON (BLAL_CALC.LICN_SEQ_NBR = LICENCE.LICN_SEQ_NBR)
	  LEFT JOIN
	  (  SELECT LICN_SEQ_NBR,
				SUM(COALESCE(ST_IsEmpty(SHAPE)::int, 1)) AS NO_SHAPE
		   FROM LRM_REPLICATION.LICENCE_SHAPE_EVW
	   GROUP BY LICN_SEQ_NBR) CS
		 ON (CS.LICN_SEQ_NBR = LRM_REPLICATION.LICENCE.LICN_SEQ_NBR)
		LEFT JOIN 
	(	SELECT LICN_SEQ_NBR,
		ROUND(CAST(COALESCE(SUM(ST_Area(V.SHAPE)) / 10000, 0) AS numeric), 1) AS GROSS_AREA
		FROM BCTS_STAGING.V_LRM_LICENCE_SHAPE V
		GROUP BY LICN_SEQ_NBR
	) LS
  		ON LS.LICN_SEQ_NBR = LRM_REPLICATION.LICENCE.LICN_SEQ_NBR
	WHERE LRM_REPLICATION.LICENCE_ALLOCATION.LICN_SEQ_NBR IS NOT NULL
		 
-- WHERE (   EXISTS
--              (SELECT 1
--                 FROM lrm.tfm_sys_user_data_priv
--                WHERE username = USER AND unitcode = LICENCE.divi_div_nbr)
--        OR NOT EXISTS
--              (SELECT 1
--                 FROM lrm.tfm_sys_user_data_priv
--                WHERE username = USER))

;

