CREATE OR REPLACE VIEW BCTS_STAGING.V_LICENCE AS
SELECT 
DISTINCT
--MXIAN  2022-09-22 SQ19820 update logic of REMAIN_COMMIT_VOLUME
           L.LICN_SEQ_NBR,
           L.TENT_SEQ_NBR,
           L.CTOR_SEQ_NBR,
           L.CLOC_SEQ_NBR,
           D.DIVI_SHORT_CODE
               TSO_CODE,
           D.DIVI_DIVISION_NAME
               TSO_NAME,
           M.MANU_ID
               NAV_NAME,
           L.LICN_LICENCE_ID
               LICENCE_ID,
           LK.COLU_LOOKUP_DESC
               CATEGORY,
           TN.TENT_TENURE_ID
               TENURE,
           L.LSEE_LICENSEE_ID
               LICENSEE,
           CT.CTOR_NAME
               REGISTRANT,
           CL.CLOC_CITY
               REGISTRANT_CITY,
           LKF.COLU_LOOKUP_DESC
               FIELD_TEAM,
           P.DISTRICT_NAME,
           L.DIVI_DIV_NBR,
           L.LICN_CATEGORY_ID,
           L.BLAZ_ADMIN_ZONE_ID,
           BZ.BLAZ_ADMIN_ZONE_DESC,
           L.LICN_LICENCE_STATE,
           L.LICN_LICENCE_DESC,
           L.LICN_LICENCE_TO_CUT_CODE,
           L.LINC_CERT_LEVEL_ID,
           L.LICN_DIGI_IND,
           L.LICN_SALVAGE_IND,
           L.LICN_APPORTION_TENURE_TYPE,
            (
                SELECT CASE
                WHEN DISPO_AGREEMENT IS NOT NULL THEN
                APPO_TENURE_TYPE || '-' || DISPO_AGREEMENT
                ELSE
                APPO_TENURE_TYPE
                END AS result
                FROM LRM_REPLICATION.APPORTIONMENT
                WHERE CM.COPA_COMMIT_APPO = APPO_SEQ_NBR
			) AS APPORTION_TYPE,
           PRTN.COLU_LOOKUP_DESC
               AS PARTITION_TYPE,
           (SELECT DESCRIPTION
              FROM LRM_REPLICATION.LRM_VT_COMMIT_LIC_TYPE AS VT
             WHERE CM.COPA_COMMIT_LIC_TYPE = VT.CODE)
               AS COMMIT_LICENCE_TYPE,
           PP.SUM_COPA_COMMIT_M3_VOL
               AS COMMIT_VOLUME,
           ROUND (BLAL_CALC.CRUISE_VOLUME + BLAL_CALC.REMAIN_VOLUME - SL.SUM_LIC_COPA_COMMIT_M3_VOL)
               AS REMAIN_COMMIT_VOLUME,
           HH.BCHH_BILLING_YEAR  AS BCHH_BILLING_YEAR,
           M.MANU_SEQ_NBR
      FROM LRM_REPLICATION.DIVISION                  D
           INNER JOIN LRM_REPLICATION.LICENCE                   L
		   ON D.DIVI_DIV_NBR = L.DIVI_DIV_NBR
		   INNER JOIN  LRM_REPLICATION.LICENCE_ALLOCATION        LA
		   ON L.LICN_SEQ_NBR = LA.LICN_SEQ_NBR
		   LEFT OUTER JOIN LRM_REPLICATION.MANAGEMENT_UNIT           M
		   ON LA.MANU_SEQ_NBR = M.MANU_SEQ_NBR
		   LEFT OUTER JOIN LRM_REPLICATION.CODE_LOOKUP               LK
		   ON L.LICN_CATEGORY_ID = LK.COLU_LOOKUP_ID
		   AND LK.COLU_LOOKUP_TYPE = 'LICA'
		   LEFT OUTER JOIN LRM_REPLICATION.TENURE_TYPE               TN
		   ON L.TENT_SEQ_NBR = TN.TENT_SEQ_NBR
		   LEFT OUTER JOIN LRM_REPLICATION.CTOR_CONTRACTOR           CT
		   ON L.CTOR_SEQ_NBR = CT.CTOR_SEQ_NBR
		   LEFT OUTER JOIN LRM_REPLICATION.CTOR_CONTRACTOR_LOCATION  CL
		   ON L.CLOC_SEQ_NBR = CL.CTOR_SEQ_NBR
		   AND L.CTOR_SEQ_NBR = CL.CLOC_SEQ_NBR
		   LEFT OUTER JOIN LRM_REPLICATION.CODE_LOOKUP               LKF
		   ON L.LICN_FIELD_TEAM_ID = LKF.COLU_LOOKUP_ID
		   AND LKF.COLU_LOOKUP_TYPE = 'FDTM'
		   
		   LEFT OUTER JOIN
		   (
				SELECT B.LICN_SEQ_NBR,
				MAX (A.ADMIN_DSCT_DISTRICT_NAME)     AS DISTRICT_NAME
				FROM LRM_REPLICATION.CUT_PERMIT A
				INNER JOIN LRM_REPLICATION.PERMIT_ALLOCATION B
				ON A.PERM_SEQ_NBR = B.PERM_SEQ_NBR
				GROUP BY B.LICN_SEQ_NBR
		   ) P
		   ON LA.LICN_SEQ_NBR = P.LICN_SEQ_NBR
		   LEFT OUTER JOIN LRM_REPLICATION.BLOCK_ADMIN_ZONE          BZ
		   ON L.DIVI_DIV_NBR = BZ.DIVI_DIV_NBR
		   AND L.BLAZ_ADMIN_ZONE_ID = BZ.BLAZ_ADMIN_ZONE_ID
		   LEFT OUTER JOIN BCTS_STAGING.V_LRM_COMMITMENTS         CM
		   ON  L.LICN_SEQ_NBR = CM.LICN_SEQ_NBR
		   LEFT OUTER JOIN LRM_REPLICATION.CODE_LOOKUP               PRTN
		   ON CM.COPA_PARTITION = PRTN.COLU_LOOKUP_ID
		   AND PRTN.COLU_LOOKUP_TYPE = 'PRTN'
		   LEFT OUTER JOIN 
		   (
			SELECT  STRING_AGG( BHH.BCHH_BILLING_YEAR::TEXT,', ' ORDER BY MA.LICN_SEQ_NBR ) BCHH_BILLING_YEAR,
        	MA.LICN_SEQ_NBR                 AS LICN_SEQ_NBR
			FROM (SELECT DISTINCT BCHH_BILLING_YEAR, MARK_SEQ_NBR 
				FROM LRM_REPLICATION.BCTS_HARVEST_HISTORY) BHH
			INNER JOIN LRM_REPLICATION.MARK                M
			ON BHH.MARK_SEQ_NBR = M.MARK_SEQ_NBR
			INNER JOIN LRM_REPLICATION.MARK_ALLOCATION     MA
			ON M.MARK_SEQ_NBR = MA.MARK_SEQ_NBR
			GROUP BY MA.LICN_SEQ_NBR
		   ) HH
		   ON L.LICN_SEQ_NBR = HH.LICN_SEQ_NBR
		   LEFT OUTER JOIN 
		   (
			SELECT SUM (COPA_COMMIT_M3_VOL)     SUM_LIC_COPA_COMMIT_M3_VOL,
			       LICN_SEQ_NBR
			FROM LRM_REPLICATION.COMMITMENT_PARTITION CP
			INNER JOIN LRM_REPLICATION.COMMITMENTS C
			ON CP.COMMIT_SEQ_NBR = C.COMMIT_SEQ_NBR
			GROUP BY LICN_SEQ_NBR
		   ) SL
		   ON L.LICN_SEQ_NBR = SL.LICN_SEQ_NBR
		   LEFT OUTER JOIN 
		   (
			SELECT SUM (COALESCE(BLAL_CRUISE_M3_VOL, 0))     CRUISE_VOLUME,
			SUM (COALESCE(BLAL_RW_VOL,0)) REMAIN_VOLUME,
			LICN_SEQ_NBR
			FROM LRM_REPLICATION.BLOCK_ALLOCATION
			GROUP BY LICN_SEQ_NBR
		   ) BLAL_CALC
		   ON L.LICN_SEQ_NBR = BLAL_CALC.LICN_SEQ_NBR
		   LEFT OUTER JOIN 
		      (  SELECT SUM (COPA_COMMIT_M3_VOL)     SUM_COPA_COMMIT_M3_VOL,
                     COMMIT_SEQ_NBR
                FROM LRM_REPLICATION.COMMITMENT_PARTITION
            GROUP BY COMMIT_SEQ_NBR) PP
			ON CM.COMMIT_SEQ_NBR = PP.COMMIT_SEQ_NBR

           
    
		   
            
          
           
           
           
           
           
           
    
           

