CREATE OR REPLACE VIEW BCTS_STAGING.V_LRM_COMMITMENTS AS

SELECT 
C.LICN_SEQ_NBR,
C.COMMIT_SEQ_NBR,
C.COPA_PARTITION,
C.COPA_COMMIT_APPO,
P.SUM_COPA_COMMIT_M3_VOL                AS V_COPA_COMMIT_M3_VOL,
ROUND (
	(BLAL_CALC.CRUISE_VOLUME
   + BLAL_CALC.REMAIN_VOLUME)
   - SL.SUM_LIC_COPA_COMMIT_M3_VOL)    AS V_REMAIN_COMMIT_M3_VOL,
C.MODIFIEDBY,
C.MODIFIEDON,
C.MODIFIEDUSING,
C.CREATEDBY,
C.CREATEDON,
C.CREATEDUSING,
C.MANU_SEQ_NBR,
C.COPA_COMMIT_LIC_TYPE
FROM LRM_REPLICATION.COMMITMENTS    C
INNER JOIN BCTS_STAGING.V_LRM_LICENCE  L
ON C.LICN_SEQ_NBR = L.LICN_SEQ_NBR
LEFT JOIN 
(  
SELECT 
SUM (COPA_COMMIT_M3_VOL)     SUM_COPA_COMMIT_M3_VOL,
COMMIT_SEQ_NBR               AS P_COMMIT_SEQ_NBR
FROM LRM_REPLICATION.COMMITMENT_PARTITION
GROUP BY COMMIT_SEQ_NBR 
) P
ON P.P_COMMIT_SEQ_NBR = C.COMMIT_SEQ_NBR
LEFT JOIN 
(
    SELECT 
    SUM (COALESCE (COPA_COMMIT_M3_VOL, 0)) AS SUM_LIC_COPA_COMMIT_M3_VOL,
    LICN_SEQ_NBR AS LICN_SEQ_NBR
    FROM LRM_REPLICATION.COMMITMENT_PARTITION CP
    INNER JOIN LRM_REPLICATION.COMMITMENTS C
    ON CP.COMMIT_SEQ_NBR = C.COMMIT_SEQ_NBR
    GROUP BY LICN_SEQ_NBR
) SL
ON SL.LICN_SEQ_NBR = L.LICN_SEQ_NBR
INNER JOIN 
(  
    SELECT SUM (COALESCE (BLAL_CRUISE_M3_VOL, 0))     CRUISE_VOLUME,
		 SUM (COALESCE (BLAL_RW_VOL, 0))            REMAIN_VOLUME,
		 LICN_SEQ_NBR
	FROM LRM_REPLICATION.BLOCK_ALLOCATION
GROUP BY LICN_SEQ_NBR
) BLAL_CALC
ON BLAL_CALC.LICN_SEQ_NBR = L.LICN_SEQ_NBR;