WITH
SPLIT_SPECIES AS (
    SELECT 
        LICENCE_ID,
        BLOCK_ID,
        BLOCK_VOLUME,
        GEOGRAPHIC_LOCATION, 
        FIELD_TEAM,
        TRIM(REGEXP_SUBSTR(SPECIES_COMPOSITION, '[^;]+', 1, LEVEL)) AS SPECIES_DETAIL
    FROM 
        forestview.SV_SALES_SCHEDULE 
    CONNECT BY 
        REGEXP_SUBSTR(SPECIES_COMPOSITION, '[^;]+', 1, LEVEL) IS NOT NULL 
        AND PRIOR BLOCK_ID = BLOCK_ID
        AND PRIOR LICENCE_ID = LICENCE_ID
        AND PRIOR DBMS_RANDOM.VALUE IS NOT NULL
),
PARSED_SPECIES AS (
    SELECT 
        LICENCE_ID,
        BLOCK_ID,
        BLOCK_VOLUME,
        REGEXP_SUBSTR(TRIM(SPECIES_DETAIL), '^[A-Z]+') AS SPECIES_CD,
        TO_NUMBER(REGEXP_SUBSTR(SPECIES_DETAIL, '[0-9.]+')) AS SPECIES_PCT
    FROM 
        SPLIT_SPECIES
    WHERE 
        BLOCK_VOLUME IS NOT NULL AND BLOCK_VOLUME > 0
),

LICENCE_VOLUME AS (
    SELECT 
        LICENCE_ID,
        SUM(BLOCK_VOLUME) AS TOTAL_VOLUME
    FROM 
        forestview.SV_SALES_SCHEDULE
    WHERE 
        BLOCK_VOLUME IS NOT NULL AND BLOCK_VOLUME > 0
    GROUP BY 
        LICENCE_ID
),

CALC_WEIGHT AS (
    SELECT 
        p.LICENCE_ID,
        p.SPECIES_CD,
        SUM(p.BLOCK_VOLUME * p.SPECIES_PCT) AS WEIGHTED_PCT_NUMERATOR,
        lv.TOTAL_VOLUME,
        CASE 
            WHEN lv.TOTAL_VOLUME = 0 THEN 0 
            ELSE SUM(p.BLOCK_VOLUME * p.SPECIES_PCT) / lv.TOTAL_VOLUME
        END AS FINAL_PCT
    FROM 
        PARSED_SPECIES p
    JOIN LICENCE_VOLUME lv
        ON p.LICENCE_ID = lv.LICENCE_ID
    GROUP BY 
        p.LICENCE_ID, p.SPECIES_CD, lv.TOTAL_VOLUME
),

SPECIES AS (
    SELECT 
        LICENCE_ID,
        LISTAGG(
            SPECIES_CD || ' ' || ROUND(FINAL_PCT, 0) || '%', 
            ', '
        ) WITHIN GROUP (ORDER BY FINAL_PCT DESC) AS SPECIES
    FROM 
        CALC_WEIGHT
    WHERE ROUND(FINAL_PCT,0) > 0  
    GROUP BY 
        LICENCE_ID
)


SELECT DISTINCT 
    AUC_DATA.LICENCE_ID,
    ss.GEOGRAPHIC_LOCATION, 
    ss.FIELD_TEAM, 
    species.SPECIES
FROM 
    forestview.SV_SALES_SCHEDULE ss
LEFT JOIN SPECIES
    ON species.LICENCE_ID = ss.LICENCE_ID
    
RIGHT JOIN (
    SELECT DISTINCT LICENCE_ID
    FROM forestview.V_LICENCE_ACTIVITY_ALL

    WHERE LICENCE_ID IN (


        'TA2792','TA2726','TA2705','TA0358','TA2378'


        
    )
) AUC_DATA
    ON AUC_DATA.LICENCE_ID = ss.LICENCE_ID;
